### ISSUE TITLE
Hero Points Settings Menu not working

### ISSUE THREAD

**Issue by dsakura** [NekroDarkmoon/optional-rules-dnd5e#46]
The other two are opening without problem. Here the error from console:
```
TypeError: An error occurred while rendering HeroPointsSettings 229. Cannot convert undefined or null to object
[Detected 4 packages: optional-rules-dnd5e, remote-highlight-ui, lib-wrapper, colorsettings]
    at Function.entries (<anonymous>)
    at HeroPointsSettings.getData (heroPointsSettings.js:27:37)
    at HeroPointsSettings._render (foundry.js:5812:29)
    at HeroPointsSettings._render (foundry.js:6532:17)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁FormApplication.prototype._render#remote-highlight-ui (hooks.js:31:14)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁FormApplication.prototype._render#0 (libWrapper-wrapper.js:189:20)
    at HeroPointsSettings.render (foundry.js:5769:10)
    at MonksSettingsConfig.onClickSubmenuWrapper (colorSetting.js:21:24)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁SettingsConfig.prototype._onClickSubmenu#0 (libWrapper-wrapper.js:189:20)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```
Many thanks

**Comment by radakaz** [comment]
I have the same issue.
foundry.js:753 TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at HeroPointsSettings.getData (heroPointsSettings.js:27:37)
    at HeroPointsSettings._render (foundry.js:5812:29)
    at HeroPointsSettings._render (foundry.js:6532:17)
    at HeroPointsSettings.render (foundry.js:5769:10)
    at SettingsConfig.onClickSubmenuWrapper (colorSetting.js:21:24)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁SettingsConfig.prototype._onClickSubmenu#0 (libWrapper-wrapper.js:189:20)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
Any ideas on a fix?

**Comment by biggusbeardus** [comment]
I too am having the same issue. My console looks exactly like the ones already posed here.

**Comment by Gvicross** [comment]
Me too
